-- --------------------- P1 - A 2019/1 ------------------------
-- Linguagem: Mysql
-- 
-- 01 Base de Dados
-- 07 Tabelas
-- 
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS p1A
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;
USE p1A;

CREATE TABLE PESSOA (
    cpf BIGINT(11) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    dtNascimento DATE NOT NULL,

    CONSTRAINT PESSOA_PK PRIMARY KEY (cpf)
) ENGINE = InnoDB;

CREATE TABLE ALUNO (
    cpfAluno BIGINT(11) NOT NULL,

    CONSTRAINT ALUNO_PK PRIMARY KEY(cpfAluno),

    CONSTRAINT ALUNO_PESSOA_FK FOREIGN KEY (cpfAluno)
      REFERENCES PESSOA (cpf)
) ENGINE = InnoDB;

CREATE TABLE DOCENTE (
    matricula BIGINT NOT NULL AUTO_INCREMENT,
    cpfDocente BIGINT(11) NOT NULL,

    CONSTRAINT DOCENTE_PK PRIMARY KEY (matricula),
    CONSTRAINT DOCENTE_UK UNIQUE(cpfDocente),

    CONSTRAINT DOCENTE_PESSOA_FK FOREIGN KEY (cpfDocente)
      REFERENCES PESSOA(cpf)
) ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE UNIVERSIDADE (
    cgc BIGINT(14) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    area VARCHAR(100) NOT NULL,
    cidade VARCHAR(50) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    cep BIGINT NOT NULL,

    CONSTRAINT UNIVERSIDADE_PK PRIMARY KEY (cgc)
) ENGINE = InnoDB;

CREATE TABLE CURSO (
    idCurso INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    areaAtuacao VARCHAR(50) NOT NULL,

    CONSTRAINT CURSO_PK PRIMARY KEY (idCurso)
) ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE telefone (
    cpf BIGINT(11) NOT NULL,
    telefone BIGINT NOT NULL,

    CONSTRAINT telefone_FK FOREIGN KEY (cpf)
      REFERENCES ALUNO(cpfAluno)
) ENGINE = InnoDB;

CREATE TABLE ADMITIDO (
    dtIngresso DATE,
    cpfAluno BIGINT(11),
    idCurso INT,
    matriculaProfessor BIGINT(11),
    cgc BIGINT(14),
    
    CONSTRAINT ADMITIDO_PK PRIMARY KEY (cgc, cpfAluno),

    CONSTRAINT ADMITIDO_CURSO_FK FOREIGN KEY (idCurso)
      REFERENCES CURSO(idCurso),
    CONSTRAINT ADMITIDO_DOCENTE_FK FOREIGN KEY (matriculaProfessor)
      REFERENCES DOCENTE(matricula),
    CONSTRAINT ADMITIDO_ALUNO_FK FOREIGN KEY (cpfAluno)
      REFERENCES ALUNO(cpfAluno),
    CONSTRAINT ADMITIDO_UNIVERSIDADE_FK FOREIGN KEY (cgc)
      REFERENCES UNIVERSIDADE(cgc)
) ENGINE = InnoDB;